[package]
name = "compli"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.5.0"
chumsky = "0.9.3"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
llvm-sys-180 = { package = "llvm-sys", version = "180", features = ["prefer-static"] }
